services:
  quant-ux-backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: quant-ux-backend-dev
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./matc.conf:/app/matc.conf
      - ./target:/app/target
      - maven-cache:/root/.m2
      - ./test:/test
      - ./logs:/logs
    ports:
      - "8082:8082"
    environment:
      QUX_IMAGE_FOLDER_USER: /test/qux-images
      QUX_IMAGE_FOLDER_APPS: /test/qux-image-apps
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: sync
          path: ./pom.xml
          target: /app/pom.xml
        - action: sync
          path: ./matc.conf
          target: /app/matc.conf

volumes:
  maven-cache:
