services:
  quant-ux-backend:
    image: quant-ux-backend:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: quant-ux-backend
    volumes:
      - ./:/usr/src/quant-ux-backend
      # Anonymous volumes to persist uploaded images across container restarts
      - /quantux/user
      - /quantux/apps
    ports:
      - "9001:9001"
    environment:
      QUX_IMAGE_FOLDER_USER: /quantux/user
      QUX_IMAGE_FOLDER_APPS: /quantux/apps
      QUX_MONGO_DB_NAME: quantux
