FROM maven:3.9-eclipse-temurin-17

WORKDIR /usr/src/quant-ux-backend

# Install file watcher tool (entr) for hot reload
RUN apt-get update && \
  apt-get install -y entr && \
  rm -rf /var/lib/apt/lists/*

# Expose port
EXPOSE 9001

# Use the entrypoint script
ENTRYPOINT ["/usr/src/quant-ux-backend/entrypoint.local.sh"]